Game
Oleg-Melnikow/tic-tac pull request #1
Opened 2020-12-04 21:13 UTC by Oleg-Melnikow

Hi, please could you review my code?

2020-12-06 15:44 UTC, artur-nikitsin reviewed
Hi! I left some comments about your code ;)

2020-12-06 15:44 UTC, artur-nikitsin commented on src/components/Board.js
> +                onClick={() => this.props.onClick(i)}
This is not good practice to add event handler using this syntax, because it will be recreated on each render

2020-12-06 15:44 UTC, artur-nikitsin commented on src/components/Board.js
> +                value={this.props.squares[i]}
You can destructure your props:
`const { squares, onClick }=this.props`

2020-12-06 15:44 UTC, artur-nikitsin commented on src/components/Board.js
> +class Board extends React.Component {
You should use functional component.

2020-12-06 15:44 UTC, artur-nikitsin commented on src/components/ControlBoard/ButtonControl.js
> +        </button>
Use destructurization:
`function ButtonControl ( {option, name } ) {  ...your awersome code...`

2020-12-06 15:44 UTC, artur-nikitsin commented on src/components/ControlBoard/ControlBoard.js
> +function ControlBoard(props) {
The same

2020-12-06 15:44 UTC, artur-nikitsin commented on src/components/History.js
> +class History extends React.Component {
Use PureComponent

2020-12-06 15:44 UTC, artur-nikitsin commented on src/components/History.js
> +                        <ButtonControl option={() => this.hide()} name={`Hide history`}/>
The same event syntax

2020-12-06 15:44 UTC, artur-nikitsin commented on src/index.js
> +    handleClick = async (i) => {
Do we need async there?

2020-12-06 15:44 UTC, artur-nikitsin commented on src/index.js
> +    reset = async () => {
The same...

2020-12-07 16:36 UTC, maximsan requested changes
Hello! There are a lot of useless `await`'s and other interesting places. Please, look through your code and fix them

2020-12-07 16:36 UTC, maximsan commented on src/components/Board.js
> +                {renderSquare(8)}
[...Array.from(Array(10).keys())].map(renderSquare)... smth like this, basically I mean you can reduce repetition here

2020-12-07 16:36 UTC, maximsan commented on src/components/ControlBoard/ButtonControl.js
> +        <button className={style.button} onClick={() => option()}>
`() => option()` - do never do this

2020-12-07 16:36 UTC, maximsan commented on src/components/ControlBoard/ControlBoard.js
> +            <ButtonControl option={reset} name={"Reset"}/>
`{ }` - brackets are redundant around string

2020-12-07 16:36 UTC, maximsan commented on src/components/Status.js
> +        status = 'Следующий ход: ' + (props.state.xIsNext ? 'X' : 'O');
Why is it Russian ?

2020-12-07 16:36 UTC, maximsan commented on src/index.js
> +        }
do this in `ComponentDidMount` and make a method

2020-12-07 16:36 UTC, maximsan commented on src/index.js
> +        await this.setState({
remove useless `await` 's

2020-12-07 16:36 UTC, maximsan commented on src/index.js
> +        this.setState({
you have to use the previous state in you calculation too

2020-12-07 16:36 UTC, maximsan commented on src/index.js
> +function calculateWinner(squares) {
move out to separate file

2020-12-07 16:36 UTC, maximsan commented on src/index.js
> +    }
It's useless, it make sense only as reusable method and in this case `state` must be passed as a parameter

2020-12-07 19:18 UTC, Oleg-Melnikow commented on src/components/ControlBoard/ButtonControl.js
> +        <button className={style.button} onClick={() => option()}>
ok, i changed it.

2020-12-07 20:11 UTC, merged